### ISSUE TITLE
Open-api: generate components with #ref?

### ISSUE THREAD

**Issue by DHFW** [ts-rest/ts-rest#421] opened 2023-10-26 18:51 UTC
Hello, is it possible to have responses generated with `#ref` components? That would make it easier to reuse the response types. Now the response types are generated "inline" like so:

```json
 "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": { ...
```

But what I want it to be is like so:
```json
"content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MyArrayType"
                }
              }
            }

```

I'm using these versions (currently latest):
"@ts-rest/core": "^3.30.4",
"@ts-rest/open-api": "^3.30.4",

Thank you!

**Comment by Gabrola** [comment] 2024-04-02 01:23
Duplicate of #366

**Closed by Gabrola** 2024-04-02 01:23 UTC
Labels: duplicate
