### ISSUE TITLE
OpenAPI Specification Generator doesn't generate Schemas - only the endpoints.

### ISSUE THREAD

**Issue by razb-viola** [ts-rest/ts-rest#422] opened 2023-11-02 06:45 UTC
This is the sample contract:

```
import { initContract } from '@ts-rest/core';
import { z } from 'zod';

const c = initContract();

export const Post = z.object({
  id: z.string(),
  title: z.string(),
  body: z.string(),
});

export const contract = c.router({
  createPost: {
    method: 'POST',
    path: '/posts',
    responses: {
      201: Post,
    },
    body: z.object({
      title: z.string(),
      body: z.string(),
    }),
    summary: 'Create a post',
  },
  getPost: {
    method: 'GET',
    path: `/posts/:id`,
    responses: {
      200: Post.nullable(),
    },
    summary: 'Get a post by id',
  },
});
```

Then I want to create Swagger Ui from it, using the OpenAPI plugin, who should generate the OAS. Like this:

```
import { contract } from './contract';
import { generateOpenApi } from "@ts-rest/open-api";

const postsApiDocs = generateOpenApi(contract, {
  info: {
    title: 'Posts API',
    version: '1.0.0',
  }
})

app.use('/docs', swaggerUi.serve, swaggerUi.setup(postsApiDocs, {
  explorer: true,
  swaggerOptions: {
    validatorUrl: null
  }
}))
```

But then when I navigate to `localhost:3333/docs`, I only see the endpoints but never the Schemas, like `Post` for example.

**Comment by ssijak** [comment] 2023-11-28 21:06
Is this something that is planned to be added?

**Comment by Gabrola** [comment] 2024-04-02 01:22
Duplicate of #366

**Closed** 2024-04-02 01:22 UTC
Labels: duplicate
