### ISSUE TITLE
Migrate to TanStack Query v5

### ISSUE THREAD

**Issue by iamyuu** [ts-rest/ts-rest#415] opened 2023-10-19 02:43 UTC
Read the announcement post here: https://tanstack.com/blog/announcing-tanstack-query-v5
Read the migration guide here: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5

**Comment by techgerm** [comment] 2023-10-26 22:09
This would be awesome! 🚀

**Comment by Talent30** [comment] 2023-10-27 03:56
Hi, @iamyuu @techgerm. I am trying to migrate it. Please join discord if you would like to help.

**Comment by michaelangeloio** [comment] 2023-11-11 16:57
One caveat to this: All of our packages are currently in sync. We'd have to break this convention to _not_  let others be forced to upgrade (should they want the latest @ts-rest/core package, for instance). 

If the community is OK with upgrading to react-query v5, I'm also cool with it, so as long as we properly communicate @ts-rest/vX will force you to upgrade react query.

**Comment by PontusAxelsson** [comment] 2023-11-14 10:19
It is peerDependency to "@tanstack/react-query": "^4.0.0", would be good if it could handle both like:
"peerDependencies": {
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "@tanstack/react-query": "^4.0.0" || "^5.0.0",
    "zod": "^3.22.3"
  },

**Comment by mxmnci** [comment] 2023-12-07 13:49
+1 on this one!

**Comment by AdhamMoussa** [comment] 2023-12-09 14:19
+1

**Comment by fruchtzwerg** [comment] 2023-12-26 19:42
I suggest to do this incrementally. v4 already supports object syntax for query options (1st item in the migration guide):
https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/react-query/src/lib/react-query.ts#L91
```
- useQuery(queryKey, dataFn, options)
+ useQuery({ queryKey, queryFn, ...options })
```

This could be done under the hood as a non-breaking change, thus supporting v4 and v5 as a peer dependency. I would imagine that this fixes 90% of use-cases.

**Comment by rjay98** [comment] 2024-05-28 21:14
@Gabrola, we're using `ts-rest` in production and loving it - thank you all for maintaining & developing this! 

Wanted to flag that `react-query` v5 is definitely a top priority for us, mostly as a way to start incorporating some of the new features (e.g., https://github.com/TanStack/query/pull/7481) which has powerful new tools for promise handling between client/server components.

**Comment by ChiefORZ** [comment] 2024-06-12 04:08
> One caveat to this: All of our packages are currently in sync. We'd have to break this convention to _not_ let others be forced to upgrade (should they want the latest @ts-rest/core package, for instance).
> 
> If the community is OK with upgrading to react-query v5, I'm also cool with it, so as long as we properly communicate @ts-rest/vX will force you to upgrade react query.

We will need to make a breaking change in the api of `@ts-rest/*` thats correct, but the package itself can offer a backward compatible layer that allows the usage of both react-query: `^4.0.0 || ^5.0.0`

**Comment by AndreyMay** [comment] 2024-06-22 21:21
+1 to the v5 upgrade

**Comment by rjay98** [comment] 2024-06-26 07:07
We've ended up migrating to RQ v5, and luckily our existing ts-rest calls work for the most part. One annoying bit is needing to specify queryKey twice if using additional query options, and useSuspenseQuery needs to be done manually. 

Example:

```
const query = api.subpath.endpoint.useQuery(
  ["query", "key"],
  { params: {} },
  { 
    queryKey: ["query", "key"], // this is required to use additional options
    gcTime: 4000
  }
)
```

Surprisingly not too bad!

**Comment by ChiefORZ** [comment] 2024-06-26 07:16
> We've ended up migrating to RQ v5, and luckily our existing ts-rest calls work for the most part. One annoying bit is needing to specify queryKey twice if using additional query options, and useSuspenseQuery needs to be done manually.
> 
> Example:
> 
> ```
> const query = api.subpath.endpoint.useQuery(
>   ["query", "key"],
>   { params: {} },
>   { 
>     queryKey: ["query", "key"], // this is required to use additional options
>     gcTime: 4000
>   }
> )
> ```
> 
> Surprisingly not too bad!

yeah the `useSuspenseQuery` is the only thing holding us back to migrate to v5 too. i tried to create a PR to provide a easier migration path, but it got closed.
https://github.com/ts-rest/ts-rest/pull/609#issue-2335108434

**Comment by Gabrola** [comment] 2024-07-22 11:10
Sorry this took so much time but wanted to do it properly. Initial support for RQ v5 has been released in `@ts-rest/react-query@v4.0.0-beta.0`. I only released it as beta, as I'm still unsure if we will release v4 for the RQ library separately, or if we wait until the rest of ts-rest v4 is ready and then release everything together in order to keep the versions synced. However, I've tested it enough and it should be production-ready. The changes to the API are documented for now in #633

**Comment by Gabrola** [comment] 2024-07-29 21:38
@shawnmclean the last `4.0.0-beta.1` release is broken, but that's coincidentally good because the API has changed a lot since then. The latest version if out now https://github.com/ts-rest/ts-rest/releases/tag/v3.49.0-beta.2 and full release to follow up soon.  A preview of the docs are here https://ts-rest-gjt9ogi2z-ts-rest.vercel.app/docs/react-query/v5-setup

**Closed** 2024-07-30 00:48 UTC

**Comment by Gabrola** [comment] 2024-07-30 06:04
@shawnmclean Can't really tell what the problem is, and the project is too big to test anything.

**Comment by Gabrola** [comment] 2024-07-30 20:05
@shawnmclean ah yes, I just looked at the code you linked and can immediately see that it's a server component. So yeah, `useQueryClient` is a hook, so it won't work on server components. You need to use `initQueryClient` as mentioned in the docs.
