### ISSUE TITLE
[query-client] Omit params property when there are no params

### ISSUE THREAD

**Issue by danielpza** [ts-rest/ts-rest#303] opened 2023-07-15 18:42 UTC
Currently we need to pass an empty object as `params` even if no param is needed:

```ts
  client.test.useQuery(["something"], {
    query: { someQuery },
    params: {}, // cannot omit param object or ts complains
  });
```

The param property should be (imo) optional when it's not needed

**Comment by oliverbutler** [comment] 2023-07-20 17:20
Hey this should be functioning already so I'm going to make as a bug and try write a failing test for this. 

Thanks!

**Comment by oliverbutler** [comment] 2023-07-26 21:37
Hey @danielpza I can't create a minimal reproduction of this my side

Can you check that you're using strict mode in TS in this app?

Also can you send the contract you used for this EP please

**Comment by oliverbutler** [comment] 2023-07-26 21:40
![Image](https://github.com/ts-rest/ts-rest/assets/47489826/524968b0-29b5-477d-858c-3e6b6da9c479)



![Image](https://github.com/ts-rest/ts-rest/assets/47489826/f5412f2e-90c8-4584-8c68-b0ea3c3ecc50)

**Comment by danielpza** [comment] 2023-07-26 23:48
Hey @oliverbutler, I was able to reproduce it here https://github.com/danielpza/ts-rest-issue-303

> Can you check that you're using strict mode in TS in this app?

Yes I'm using strict mode

**Comment by oliverbutler** [comment] 2023-07-27 07:31
Thank you! I'll take a look :)

**Comment by oliverbutler** [comment] 2023-07-27 21:46
@danielpza I've found the reason your example doesn't work and I'm not seeing the issue my side, Zod.

Right now we rely on Zod for some underlying generics in @ts-rest/core

Installing Zod, even just effectively as a dev dependency should make this work for you.

We had an issue #44 but as of right now this isn't something we're working on removing, although not relying on Zod is definitely a goal of mine for ts-rest.

**Comment by oliverbutler** [comment] 2023-07-27 21:47
Closing for right now, but I'll see if we've adequately documented this limitation (I'm doubtful we did!)

**Closed by oliverbutler** 2023-07-27 21:47 UTC
