### ISSUE TITLE
Vue Query v5.x.x.x

### ISSUE THREAD

**Issue by johnsvanda** [ts-rest/ts-rest#565] opened 2024-04-04 15:37 UTC
Is there a planned support for Vue quest by tanstack version 5?

**Comment by Gabrola** [comment] 2024-04-05 21:47
Yes soon-ish in ts-rest v4, because it is a breaking change.
Duplicate of #415

**Comment by Gabrola** [comment] 2024-04-05 21:48
Duplicate of #415

**Closed by Gabrola** 2024-04-05 21:47 UTC
Labels: enhancement
