### ISSUE TITLE
PATCH param validation

### ISSUE THREAD

**Issue by flecmen** [ts-rest/ts-rest#472] opened 2024-01-12 16:07 UTC
I have my contract defined:
```
  setSchedule: {
    method: 'PATCH',
    path: '/schedule/:scheduleId',
    pathParams: z.object({
      scheduleId: z.string().uuid(),
    }),
    body: z.object({
      ... some body,
    }),
    responses: {
      ... some responses
    }
  },
```

But when calling with valid uuid, like: `/schedule/3478ab8a-d489-474b-8450-d40014de72d5`

it always failed on param check:
```
    + Object {
    +   "bodyResult": null,
    +   "headersResult": null,
    +   "paramsResult": Object {
    +     "issues": Array [
    +       Object {
    +         "code": "invalid_type",
    +         "expected": "string",
    +         "message": "Required",
    +         "path": Array [
    +           "scheduleId",
    +         ],
    +         "received": "undefined",
    +       },
    +     ],
    +     "name": "ZodError",
    +   },
    +   "queryResult": null,
    + }
```

Workaround: changing to `PUT` method.

**Comment by Chipandcharge** [comment] 2024-03-28 14:12
Doesn’t work with PATCH or PUT … get the same Error as mentioned above. I am on version 3.36.0

**Comment by Gabrola** [comment] 2024-04-08 11:58
Can you please provide a reproducible example github repo or codesandbox/stackblitz?

**Comment by Chipandcharge** [comment] 2024-04-09 06:59
I couldn't reproduce it. But debugging it showed a probelm with the params extraction by nest/express. My contract has 2 endpoints with "similar" paths.
``` javascript
getSystems: {
      method: "GET",
      path: `/system/:org_id`,
      pathParams: z.object({
        org_id: schemaID,
      }),
      responses: {
        200: z.array(systemSchema),
      },
      summary: "Get all systems",
    },
updateSystem: {
      method: "PATCH",
      path: `/system/:id`,
      pathParams: z.object({
        id: schemaID,
      }),
      responses: {
        200: systemSchema,
      },
      body: updateSystemSchema,
      summary: "Update a new system",
    },
```
The express router extracts params in layer.js match function. There the provided path is compared against a regex and this leads to extracting the param as "org_id" instead of "id", as the regex finds two results.

The param org_id with the uuid is then passed to ts-rest and its interceptor through a context (ctx)

``` javascript
intercept(ctx, next) {
        const res = ctx.switchToHttp().getResponse();
        const req = ctx.switchToHttp().getRequest();
        const { appRoute, routeKey } = this.getAppRouteFromContext(ctx);
        const options = evaluateTsRestOptions(this.globalOptions, ctx);
        const paramsResult = core.checkZodSchema(req.params, appRoute.pathParams, {
            passThroughExtraKeys: true,
        });
        [...]
    }
```

checkZodSchema compares looks for a param named id but only get org_id. Therefore it throws an error. 

My solution is changing the endpoints path to systems/:org_id
This is better anyways.

There is a quick and dirty from last night stackblitz, that tries to reproduce the error, but doesn't :D 
https://stackblitz.com/edit/nestjs-typescript-starter-jpns8l?file=src%2Fmain.ts

**Comment by Gabrola** [comment] 2024-04-13 06:01
Looks to me like some kind of express.js bug with routing, and it might have been fixed in a later version, hence why you can't reproduce on the stackblitz. Will close for now.

**Closed by Gabrola** 2024-04-13 06:01 UTC
