### ISSUE TITLE
initQueryClient seems invalid in @ts-rest/react-query

### ISSUE THREAD

**Issue by lekinano** [ts-rest/ts-rest#66] opened 2022-10-08 11:34 UTC
Hey @oliverbutler 
First thanks for this amazing tool!
I ran an error while using `@ts-rest/react-query` : `No QueryClient set, use QueryClientProvider to set one` (nx, cra/nest)

This problem happens only with the compiled package, I have no error when I copy the client from your monorepo and then create my own lib.

**Comment by oliverbutler** [comment] 2022-10-08 11:36
Interesting! Do you have a minimal reproduction (CodeSandbox/Stackblitz or a repo) to show me?

Thanks for reporting!

**Comment by oliverbutler** [comment] 2022-10-08 11:37
I was just using 3.5.0 in production yesterday and all seemed well, so I'm interested to help you out

**Comment by lekinano** [comment] 2022-10-08 12:19
Thanks for your quick reply 😄 check the [repo](https://github.com/lekinano/nx-ts-rest-sandbox) in `apps/front/src/app/app.tsx`

**Comment by oliverbutler** [comment] 2022-10-08 15:58
Hey @lekinano, I'm taking a look now, you're right this is super weird! I've had one interesting discovery so far, if I import tanstack query like ts-rest/react-query does, with "require" I have the same issue.

<img width="553" alt="Screenshot 2022-10-08 at 16 55 19" src="https://user-images.githubusercontent.com/47489826/194716320-859d5ade-e503-4f13-95f6-006d81598fa2.png">

**Comment by oliverbutler** [comment] 2022-10-08 15:59
^ This works perfectly fine with import * as X from Y

**Comment by oliverbutler** [comment] 2022-10-08 20:02
Hey @lekinano, it took some toying around, but now all the libs are building with ESM and CommonJS support. Your issue is fixed in 3.6.0! 

Enjoy :)

**Comment by lekinano** [comment] 2022-10-09 15:23
Hey @oliverbutler, I just updated, thank you very much it works perfectly ! :)

**Comment by michaelangrivera** [comment] 2022-10-10 01:27
@oliverbutler Hi! I'm also looking to use this feature, but I'm running into the same error with Next. Could I be doing something wrong?

_app.tsx looks like:
```
const queryClient = new QueryClient()
....
    <Layout>
      <QueryClientProvider client={queryClient}>
      <Component {...pageProps} />
      </QueryClientProvider>
    </Layout>
```

pages/hello/index.tsx looks like

```

import { initQueryClient } from '@ts-rest/react-query'
import {contract} from '@project/contract'

const c = initQueryClient(contract, {
  baseUrl: 'http://localhost:3999/activitystreak-staging/us-central1/api',
  baseHeaders: {}
})

const Test = () => { 
  const { data, isLoading, error } = c.getTest.useQuery(['getTest'], {query: { testParam: 'kjhsfkjhfsdf'}}, {})
  console.log(data, 'angelo')
  return (
    <></>
  )
export default Test
````

I'm also using an NX monorepo.

**Comment by oliverbutler** [comment] 2022-10-10 07:29
@michaelangrivera to confirm, is this using 3.6.0? I'll try and replicate

**Comment by michaelangrivera** [comment] 2022-10-10 12:09
@oliverbutler yes sir!

```
    "@ts-rest/core": "^3.6.0",
    "@ts-rest/nest": "^3.6.0",
    "@ts-rest/react-query": "^3.6.0",
```

**Comment by oliverbutler** [comment] 2022-10-11 15:23
Hey @michaelangrivera , I'll try to reproduce this, it's a bit frustrating to hear we're having some issues with the bundled code in NX repos! I've seen some similar-looking issues when react-query has been used via another library. 

Bundling is admittedly not my strong suit here

**Comment by ecyrbe** [comment] 2022-10-19 17:51
hello, @oliverbutler , zodios has the same issue with next and `@tanstack/react-query`. i don't think it's nx related. because the issue was not happening before on `react-query` v3.

Here the workaround i applied :  
https://github.com/ecyrbe/zodios/issues/191

i also mentioned this bug in `@tanstack/react-query` issues, see link above.

**Comment by michaelangrivera** [comment] 2022-10-21 13:11
You're the best @ecyrbe ! Thank you !

**Comment by ecyrbe** [comment] 2022-10-23 12:53
@oliverbutler i found how to fix this on zodios. So you need to fix your package.json to declare esm and cjs properly:

``json
{
  "name": "<your lib>",
  "version": "<your version>",
  "main": "lib/index.js",
  "module": "lib/index.mjs",
  "typings": "lib/index.d.ts",
  "exports": {
    ".": {
      "import": "./lib/index.mjs",
      "require": "./lib/index.js"
    },
    "./package.json": "./package.json"
  },
  "files": [
    "lib"
  ],
  ...
}
```
so with this setup, no workaround is needed.

**Comment by oliverbutler** [comment] 2022-10-23 12:54
@ecyrbe you're a star, I've been away on holiday this last two weeks and have just got back. This will massively help!

**Closed** 2022-11-23 23:22 UTC
